### PR TITLE
update template to reflect use of 'invoke'

### PR DESCRIPTION
**Pull request by gidsg**
Reflect that we have switched to invoke to run our tasks.

### CODE REVIEW

**Review by lfdebrux — APPROVED** [review]

**Comment by gidsg** [comment]
@bjgill I think you will need to merge this.

**Review by bjgill — COMMENTED** [review]
Does this mean we've finished switching all our repos across to `invoke`?

Edit: or, at least, all the ones with CI

**Comment by gidsg** [comment]
@bjgill the intent is that this is used for new repositories/reflect best practice, so I guess it is fine, as long as we don't switch back to vanilla `make`!

**Review by bjgill — APPROVED** [review]
Thanks - makes sense.

**Pull request merged**
